title: Maison de la Poésie de Rennes
email: quentin.leclerc@maisondelapoesie-rennes.org
description: Site de la Maison de la Poésie de Rennes
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maiporennes.fr" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  category:
    output: true
  artistes:
    output: true
  journal:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

gems:
  - jekyll-liquify
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
