[[redirects]]
  from = "/espace-admin/*"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

  [[redirects]]
  from = "/espace-admin-pages/*"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

[[redirects]]
  from = "/espace-admin/*"
  to = "/login/"
  status = 302
  force = true

  [[redirects]]
  from = "/espace-admin-pages/*"
  to = "/login/"
  status = 302
  force = true

[functions]
  directory = "functions"
  node_bundler = "esbuild"